package main

import (
	"encoding/json"
	"net/http"

	"github.com/go-chi/chi/v5"
)

// Code generated by oapi-codegen (simulated for the repro). DO NOT EDIT.

type CreateCustomerJSONRequestBody struct {
	DistributorID   string `json:"distributorId"`
	DistributorName string `json:"distributorName"`
}

type ServerInterface interface {
	CreateCustomer(w http.ResponseWriter, r *http.Request, body CreateCustomerJSONRequestBody)
}

type OapiMiddlewareFunc func(http.Handler) http.Handler

type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []OapiMiddlewareFunc
}

func HandlerFromMux(si ServerInterface, r chi.Router, middlewares ...OapiMiddlewareFunc) http.Handler {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: middlewares,
	}

	r.Post("/customers", wrapper.CreateCustomer)
	return r
}

func (siw *ServerInterfaceWrapper) CreateCustomer(w http.ResponseWriter, r *http.Request) {
	addTrace(r.Context(), "oapi-handler")

	var body CreateCustomerJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		http.Error(w, "invalid json body: "+err.Error(), http.StatusBadRequest)
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCustomer(w, r, body)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}
